import { NextResponse } from "next/server";
import type { A2AAgentCard } from "../../../../../../lib/a2a";
import { getPoliciesForAgent } from "../../../../../../lib/agent-fabric";

/**
 * Google A2A Agent Card for the Clinical Summary Agent — the Salesforce
 * "Agentforce for Health" After-Visit Summary / clinical-documentation analog.
 *
 *   GET /api/agents/clinical-summary/.well-known/agent.json
 *
 * Advertised governance policies are derived from the Agent Fabric registry
 * (appliesTo) rather than hand-listed, so the discovery document can't drift
 * from what the /tasks handler enforces.
 */

const HOST = process.env.NEXT_PUBLIC_SITE_URL ?? "https://pause-health.ai";
const FABRIC_AGENT_ID = "clinical-summary-agent";

const CARD: A2AAgentCard = {
  name: "Clinical Summary Agent",
  description:
    "Post-visit, COMPOSES the outputs the other agents already produced (the intake, the Care Router pathway, an optional validated-instrument assessment, an optional instantiated care plan, and any detected care gaps) into two artifacts — a patient-friendly After-Visit Summary and a clinician handoff note — and phrases them with live Anthropic Claude, falling back to a DETERMINISTIC scripted composition (with a recorded fallbackReason) when ANTHROPIC_API_KEY is unset or the API call fails. The Salesforce 'Agentforce for Health' After-Visit Summary / clinical-documentation analog and the THIRD live-Claude agent on Pause's Agent Fabric. Context assembly is a pure function of the provided lifecycle inputs (no randomness, no clock) and gathers ONLY facts present in the inputs — the real grounding guarantee — so a summary can only assert what the upstream agents established; every summary traces to a defined source record, never a fabricated one. The agent is non-prescriptive and commits no clinical action (it re-states existing records for two audiences and requires clinician review). Both artifacts are illustrative/synthetic, clearly labeled — NOT a certified clinical-documentation engine. Enforces, via the Pause Agent Fabric, that every summary traces to a source record (no fabrication), that the serving model is on the approved allow-list (Claude Sonnet / Opus), that no clinical action is committed without a clinician, and that grounding requires an ai-decision-support consent; every turn is HIPAA-audited.",
  url: `${HOST}/api/agents/clinical-summary`,
  provider: {
    organization: "Salesforce (via Pause-Health.ai)",
    url: "https://pause-health.ai"
  },
  version: "0.1.0",
  capabilities: {
    streaming: false,
    pushNotifications: false,
    stateTransitionHistory: true
  },
  defaultInputModes: ["data"],
  defaultOutputModes: ["text", "data"],
  skills: [
    {
      id: "compose-after-visit-summary-and-handoff",
      name: "Compose an after-visit summary + clinician handoff",
      description:
        "Given the lifecycle outputs (intake, Care Router pathway, optional assessment / care plan / care gaps), returns a patient-friendly After-Visit Summary and a clinician handoff note composed DETERMINISTICALLY from ONLY the facts present in the inputs — every summary traces to a defined source record (never fabricated) — with the phrasing generated by live Anthropic Claude and a deterministic scripted fallback (via + fallbackReason recorded). Non-prescriptive; commits no clinical action.",
      inputModes: ["data"],
      outputModes: ["text", "data"],
      tags: [
        "clinical-summary",
        "after-visit-summary",
        "handoff",
        "menopause",
        "clinical",
        "claude",
        "summarization",
        "health-cloud"
      ]
    }
  ],
  pauseGovernance: {
    fabricRegisteredAs: FABRIC_AGENT_ID,
    policies: getPoliciesForAgent(FABRIC_AGENT_ID).map((p) => p.id)
  }
};

export async function GET() {
  return NextResponse.json(CARD, {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "public, s-maxage=300, stale-while-revalidate=600"
    }
  });
}
